town_to_planning_region = {
    "Andover": "Capitol Planning Region",
    "Ansonia": "Naugatuck Valley Planning Region",
    "Ashford": "Northeastern Connecticut Planning Region",
    "Avon": "Capitol Planning Region",
    "Baltic": "Southeastern Connecticut Planning Region",
    "Barkhamsted": "Northwest Hills Planning Region",
    "Beacon Falls": "Naugatuck Valley Planning Region",
    "Berlin": "Capitol Planning Region",
    "Bethany": "South Central Connecticut Planning Region",
    "Bethel": "Western Connecticut Planning Region",
    "Bethlehem": "Naugatuck Valley Planning Region",
    "Bethlehem Village": "Naugatuck Valley Planning Region",
    "Blue Hills": "South Central Connecticut Planning Region",
    "Bolton": "Capitol Planning Region",
    "Bozrah": "Southeastern Connecticut Planning Region",
    "Branford": "South Central Connecticut Planning Region",
    "Branford Center": "South Central Connecticut Planning Region",
    "Bridgeport": "Greater Bridgeport Planning Region",
    "Bridgewater": "Western Connecticut Planning Region",
    "Bristol": "Naugatuck Valley Planning Region",
    "Brookfield": "Western Connecticut Planning Region",
    "Brooklyn": "Northeastern Connecticut Planning Region",
    "Burlington": "Northwest Hills Planning Region",
    "Byram": "Western Connecticut Planning Region",
    "Canaan": "Northwest Hills Planning Region",
    "Canton": "Capitol Planning Region",
    "Canton Valley": "Capitol Planning Region",
    "Canterbury": "Northeastern Connecticut Planning Region",
    "Central Waterford": "Southeastern Connecticut Planning Region",
    "Chaplin": "Northeastern Connecticut Planning Region",
    "Cheshire": "Naugatuck Valley Planning Region",
    "Cheshire Village": "Naugatuck Valley Planning Region",
    "Chester": "Lower Connecticut River Valley Planning Region",
    "Chester Center": "Lower Connecticut River Valley Planning Region",
    "City of Milford (balance)" : "South Central Connecticut Planning Region",
    "Clinton": "Lower Connecticut River Valley Planning Region",
    "Colchester": "Southeastern Connecticut Planning Region",
    "Colebrook": "Northwest Hills Planning Region",
    "Collinsville": "Northwest Hills Planning Region",
    "Columbia": "Capitol Planning Region",
    "Conning Towers-Nautilus Park": "Southeastern Connecticut Planning Region",
    "Cornwall": "Northwest Hills Planning Region",
    "Cos Cob": "Western Connecticut Planning Region",
    "Coventry": "Capitol Planning Region",
    "Coventry Lake": "Capitol Planning Region",
    "Cromwell": "Lower Connecticut River Valley Planning Region",
    "Crystal Lake": "Naugatuck Valley Planning Region",
    "Danbury": "Western Connecticut Planning Region",
    "Danielson": "Northeastern Connecticut Planning Region",
    "Darien": "Western Connecticut Planning Region",
    "Deep River": "Lower Connecticut River Valley Planning Region",
    "Deep River Center": "Lower Connecticut River Valley Planning Region",
    "Derby": "Naugatuck Valley Planning Region",
    "Durham": "Lower Connecticut River Valley Planning Region",
    "Eastford": "Northeastern Connecticut Planning Region",
    "East Granby": "Capitol Planning Region",
    "East Haddam": "Lower Connecticut River Valley Planning Region",
    "East Hampton": "Lower Connecticut River Valley Planning Region",
    "East Hartford": "Capitol Planning Region",
    "East Haven": "South Central Connecticut Planning Region",
    "East Lyme": "Southeastern Connecticut Planning Region",
    "East Norwalk": "Western Connecticut Planning Region",
    "Easton": "Greater Bridgeport Planning Region",
    "East Windsor": "Capitol Planning Region",
    "Ellington": "Capitol Planning Region",
    "Enfield": "Capitol Planning Region",
    "Essex": "Lower Connecticut River Valley Planning Region",
    "Essex Village": "Lower Connecticut River Valley Planning Region",
    "Fairfield": "Greater Bridgeport Planning Region",
    "Farmington": "Capitol Planning Region",
    "Franklin": "Southeastern Connecticut Planning Region",
    "Gales Ferry": "Southeastern Connecticut Planning Region",
    "Georgetown": "Western Connecticut Planning Region",
    "Glastonbury": "Capitol Planning Region",
    "Glastonbury Center": "Capitol Planning Region",
    "Glenville": "Western Connecticut Planning Region",
    "Goshen": "Northwest Hills Planning Region",
    "Granby": "Capitol Planning Region",
    "Greenwich": "Western Connecticut Planning Region",
    "Griswold": "Southeastern Connecticut Planning Region",
    "Groton": "Southeastern Connecticut Planning Region",
    "Guilford": "South Central Connecticut Planning Region",
    "Guilford Center": "South Central Connecticut Planning Region",
    "Haddam": "Lower Connecticut River Valley Planning Region",
    "Hamden": "South Central Connecticut Planning Region",
    "Hampton": "Northeastern Connecticut Planning Region",
    "Hartford": "Capitol Planning Region",
    "Hartland": "Northwest Hills Planning Region",
    "Harwinton": "Northwest Hills Planning Region",
    "Hazardville": "Capitol Planning Region",
    "Hebron": "Capitol Planning Region",
    "Heritage Village": "Naugatuck Valley Planning Region",
    "Higganum": "Lower Connecticut River Valley Planning Region",
    "Jewett City": "Southeastern Connecticut Planning Region",
    "Kent": "Northwest Hills Planning Region",
    "Kensington": "Capitol Planning Region",
    "Killingly": "Northeastern Connecticut Planning Region",
    "Killingly Center": "Northeastern Connecticut Planning Region",
    "Killingworth": "Lower Connecticut River Valley Planning Region",
    "Lake Pocotopaug": "Capitol Planning Region",
    "Lebanon": "Southeastern Connecticut Planning Region",
    "Ledyard": "Southeastern Connecticut Planning Region",
    "Ledyard Center": "Southeastern Connecticut Planning Region",
    "Lisbon": "Southeastern Connecticut Planning Region",
    "Litchfield": "Northwest Hills Planning Region",
    "Long Hill": "Western Connecticut Planning Region",
    "Lyme": "Lower Connecticut River Valley Planning Region",
    "Madison": "South Central Connecticut Planning Region",
    "Madison Center": "South Central Connecticut Planning Region",
    "Manchester": "Capitol Planning Region",
    "Mansfield": "Capitol Planning Region",
    "Mansfield City": "Capitol Planning Region",
    "Marlborough": "Capitol Planning Region",
    "Meriden": "South Central Connecticut Planning Region",
    "Middlebury": "Naugatuck Valley Planning Region",
    "Middlefield": "Lower Connecticut River Valley Planning Region",
    "Middletown": "Lower Connecticut River Valley Planning Region",
    "Milford": "South Central Connecticut Planning Region",
    "Monroe": "Greater Bridgeport Planning Region",
    "Montville": "Southeastern Connecticut Planning Region",
    "Montville Center": "Southeastern Connecticut Planning Region",
    "Morris": "Northwest Hills Planning Region",
    "Mystic": "Southeastern Connecticut Planning Region",
    "Naugatuck": "Naugatuck Valley Planning Region",
    "Newington":"Capitol Planning Region",
    "New Britain": "Capitol Planning Region",
    "New Canaan": "Western Connecticut Planning Region",
    "New Fairfield": "Western Connecticut Planning Region",
    "New Hartford": "Northwest Hills Planning Region",
    "New Hartford Center": "Northwest Hills Planning Region",
    "New Haven": "South Central Connecticut Planning Region",
    "New London": "Southeastern Connecticut Planning Region",
    "New Milford": "Western Connecticut Planning Region",
    "New Preston": "Western Connecticut Planning Region",
    "Newtown": "Western Connecticut Planning Region",
    "Niantic": "Southeastern Connecticut Planning Region",
    "Noank": "Southeastern Connecticut Planning Region",
    "Norfolk": "Northwest Hills Planning Region",
    "North Branford": "South Central Connecticut Planning Region",
    "North Canaan": "Northwest Hills Planning Region",
    "North Granby": "Capitol Planning Region",
    "North Haven": "South Central Connecticut Planning Region",
    "North Stonington": "Southeastern Connecticut Planning Region",
    "North Stamford": "Western Connecticut Planning Region",
    "Northwest Harwinton": "Northwest Hills Planning Region",
    "Norwalk": "Western Connecticut Planning Region",
    "Norwich": "Southeastern Connecticut Planning Region",
    "Oakdale": "Western Connecticut Planning Region",
    "Oakland": "Western Connecticut Planning Region",
    "Oakville": "Naugatuck Valley Planning Region",
    "Old Greenwich": "Western Connecticut Planning Region",
    "Old Lyme": "Lower Connecticut River Valley Planning Region",
    "Old Mystic": "Southeastern Connecticut Planning Region",
    "Old Saybrook": "Lower Connecticut River Valley Planning Region",
    "Old Saybrook Center": "Lower Connecticut River Valley Planning Region",
    "Orange": "South Central Connecticut Planning Region",
    "Oxoboxo River": "Southeastern Connecticut Planning Region",
    "Oxford": "Naugatuck Valley Planning Region",
    "Pawcatuck": "Southeastern Connecticut Planning Region",
    "Plainfield": "Northeastern Connecticut Planning Region",
    "Plainfield Village": "Northeastern Connecticut Planning Region",
    "Plainville": "Capitol Planning Region",
    "Plymouth": "Naugatuck Valley Planning Region",
    "Poquonock Bridge": "Capitol Planning Region",
    "Pomfret": "Northeastern Connecticut Planning Region",
    "Portland": "Lower Connecticut River Valley Planning Region",
    "Preston": "Southeastern Connecticut Planning Region",
    "Preston City": "Southeastern Connecticut Planning Region",
    "Prospect": "Naugatuck Valley Planning Region",
    "Putnam": "Northeastern Connecticut Planning Region",
    "Redding": "Western Connecticut Planning Region",
    "Ridgefield": "Western Connecticut Planning Region",
    "Riverside": "Western Connecticut Planning Region",
    "Rockville": "Capitol Planning Region",
    "Rocky Hill": "Capitol Planning Region",
    "Roxbury": "Northwest Hills Planning Region",
    "Salem": "Southeastern Connecticut Planning Region",
    "Salmon Brook": "Capitol Planning Region",
    "Salisbury": "Northwest Hills Planning Region",
    "Saybrook Manor": "Lower Connecticut River Valley Planning Region",
    "Scotland": "Northeastern Connecticut Planning Region",
    "Seymour": "Naugatuck Valley Planning Region",
    "Sharon": "Northwest Hills Planning Region",
    "Shelton": "Naugatuck Valley Planning Region",
    "Sherman": "Western Connecticut Planning Region",
    "Sherwood Manor": "South Central Connecticut Planning Region",
    "Simsbury": "Capitol Planning Region",
    "Simsbury Center": "Capitol Planning Region",
    "Somers": "Capitol Planning Region",
    "South Woodstock": "Northeastern Connecticut Planning Region",
    "South Windham": "Northeastern Connecticut Planning Region",
    "Southbury": "Naugatuck Valley Planning Region",
    "South Coventry": "Capitol Planning Region",
    "South Windsor": "Capitol Planning Region",
    "Southwood Acres": "Capitol Planning Region",
    "Southport": "Greater Bridgeport Planning Region",
    "Sprague": "Southeastern Connecticut Planning Region",
    "Stafford": "Capitol Planning Region",
    "Stafford Springs": "Capitol Planning Region",
    "Stamford": "Western Connecticut Planning Region",
    "Stonington": "Southeastern Connecticut Planning Region",
    "Storrs": "Capitol Planning Region",
    "Stratford": "Greater Bridgeport Planning Region",
    "Suffield": "Capitol Planning Region",
    "Suffield Depot": "Capitol Planning Region",
    "Tariffville": "Capitol Planning Region",
    "Terramuggus": "Capitol Planning Region",
    "Terryville": "Naugatuck Valley Planning Region",
    "Thomaston": "Naugatuck Valley Planning Region",
    "Thompson": "Northeastern Connecticut Planning Region",
    "Thompsonville": "Capitol Planning Region",
    "Tolland": "Capitol Planning Region",
    "Torrington": "Northwest Hills Planning Region",
    "Trumbull": "Greater Bridgeport Planning Region",
    "Union": "Northeastern Connecticut Planning Region",
    "Uncasville": "Southeastern Connecticut Planning Region",
    "Vernon": "Capitol Planning Region",
    "Voluntown": "Northeastern Connecticut Planning Region",
    "Wallingford": "South Central Connecticut Planning Region",
    "Wallingford Center": "South Central Connecticut Planning Region",
    "Wauregan": "Northeastern Connecticut Planning Region",
    "Waterbury": "Naugatuck Valley Planning Region",
    "Waterford": "Southeastern Connecticut Planning Region",
    "Watertown": "Naugatuck Valley Planning Region",
    "Weatogue": "Capitol Planning Region",
    "West Simsbury": "Capitol Planning Region",
    "West Torrington": "Northwest Hills Planning Region",
    "Westbrook": "Lower Connecticut River Valley Planning Region",
    "Westbrook Center": "Lower Connecticut River Valley Planning Region",
    "West Hartford": "Capitol Planning Region",
    "West Haven": "South Central Connecticut Planning Region",
    "Weston": "Western Connecticut Planning Region",
    "Westport": "Western Connecticut Planning Region",
    "Wethersfield": "Capitol Planning Region",
    "Willington": "Capitol Planning Region",
    "Willimantic": "Capitol Planning Region",
    "Wilton": "Western Connecticut Planning Region",
    "Winchester": "Northwest Hills Planning Region",
    "Winsted": "Northwest Hills Planning Region",
    "Windham": "Southeastern Connecticut Planning Region",
    "Windsor": "Capitol Planning Region",
    "Windsor Locks": "Capitol Planning Region",
    "Wolcott": "Naugatuck Valley Planning Region",
    "Woodbridge": "South Central Connecticut Planning Region",
    "Woodmont": "Greater Bridgeport Planning Region",
    "Woodbury": "Naugatuck Valley Planning Region",
    "Woodbury Center": "Naugatuck Valley Planning Region",
    "Woodstock": "Northeastern Connecticut Planning Region"
}