town_to_historical_county = {
    "Andover": "Tolland County",
    "Ansonia": "New Haven County",
    "Ashford": "Windham County",
    "Avon": "Hartford County",
    "Baltic": "New London County",
    "Barkhamsted": "Litchfield County",
    "Beacon Falls": "New Haven County",
    "Berlin": "Hartford County",
    "Bethany": "New Haven County",
    "Bethel": "Fairfield County",
    "Bethlehem": "Litchfield County",
    "Bethlehem Village": "Litchfield County",
    "Blue Hills": "Hartford County",
    "Bolton": "Tolland County",
    "Bozrah": "New London County",
    "Branford": "New Haven County",
    "Branford Center": "New Haven County",
    "Bridgeport": "Fairfield County",
    "Bridgewater": "Litchfield County",
    "Bristol": "Hartford County",
    "Brookfield": "Fairfield County",
    "Brooklyn": "Windham County",
    "Burlington": "Hartford County",
    "Byram": "Fairfield County",
    "Canaan": "Litchfield County",
    "Canton": "Hartford County",
    "Canton Valley": "Hartford County",
    "Canterbury": "Windham County",
    "Central Waterford": "New London County",
    "Chaplin": "Windham County",
    "Cheshire": "New Haven County",
    "Cheshire Village": "New Haven County",
    "Chester": "Middlesex County",
    "Chester Center": "Middlesex County",
    "City of Milford (balance)": "New Haven County",
    "Clinton": "Middlesex County",
    "Colchester": "New London County",
    "Colebrook": "Litchfield County",
    "Collinsville": "Hartford County",
    "Columbia": "Tolland County",
    "Conning Towers-Nautilus Park": "New London County",
    "Cornwall": "Litchfield County",
    "Cos Cob": "Fairfield County",
    "Coventry": "Tolland County",
    "Coventry Lake": "Tolland County",
    "Cromwell": "Middlesex County",
    "Crystal Lake": "Tolland County",
    "Danbury": "Fairfield County",
    "Danielson": "Windham County",
    "Darien": "Fairfield County",
    "Deep River": "Middlesex County",
    "Deep River Center": "Middlesex County",
    "Derby": "New Haven County",
    "Durham": "Middlesex County",
    "Eastford": "Windham County",
    "East Granby": "Hartford County",
    "East Haddam": "Middlesex County",
    "East Hampton": "Middlesex County",
    "East Hartford": "Hartford County",
    "East Haven": "New Haven County",
    "East Lyme": "New London County",
    "East Norwalk": "Fairfield County",
    "Easton": "Fairfield County",
    "East Windsor": "Hartford County",
    "Ellington": "Tolland County",
    "Enfield": "Hartford County",
    "Essex": "Middlesex County",
    "Essex Village": "Middlesex County",
    "Fairfield": "Fairfield County",
    "Farmington": "Hartford County",
    "Franklin": "New London County",
    "Gales Ferry": "New London County",
    "Georgetown": "Fairfield County",
    "Glastonbury": "Hartford County",
    "Glastonbury Center": "Hartford County",
    "Glenville": "Fairfield County",
    "Goshen": "Litchfield County",
    "Granby": "Hartford County",
    "Greenwich": "Fairfield County",
    "Griswold": "New London County",
    "Groton": "New London County",
    "Guilford": "New Haven County",
    "Guilford Center": "New Haven County",
    "Haddam": "Middlesex County",
    "Hamden": "New Haven County",
    "Hampton": "Windham County",
    "Hartford": "Hartford County",
    "Hartland": "Hartford County",
    "Harwinton": "Litchfield County",
    "Hazardville": "Hartford County",
    "Hebron": "Tolland County",
    "Heritage Village": "New Haven County",
    "Higganum": "Middlesex County",
    "Jewett City": "New London County",
    "Kent": "Litchfield County",
    "Kensington": "Hartford County",
    "Killingly": "Windham County",
    "Killingly Center": "Windham County",
    "Killingworth": "Middlesex County",
    "Lake Pocotopaug": "Middlesex County",
    "Lebanon": "New London County",
    "Ledyard": "New London County",
    "Ledyard Center": "New London County",
    "Lisbon": "New London County",
    "Litchfield": "Litchfield County",
    "Long Hill": "Fairfield County",
    "Lyme": "New London County",
    "Madison": "New Haven County",
    "Madison Center": "New Haven County",
    "Manchester": "Hartford County",
    "Mansfield": "Tolland County",
    "Mansfield City": "Tolland County",
    "Marlborough": "Hartford County",
    "Meriden": "New Haven County",
    "Middlebury": "New Haven County",
    "Middlefield": "Middlesex County",
    "Middletown": "Middlesex County",
    "Milford": "New Haven County",
    "Monroe": "Fairfield County",
    "Montville": "New London County",
    "Montville Center": "New London County",
    "Morris": "Litchfield County",
    "Mystic": "New London County",
    "Naugatuck": "New Haven County",
    "Newington": "Hartford County",
    "New Britain": "Hartford County",
    "New Canaan": "Fairfield County",
    "New Fairfield": "Fairfield County",
    "New Hartford": "Litchfield County",
    "New Hartford Center": "Litchfield County",
    "New Haven": "New Haven County",
    "New London": "New London County",
    "New Milford": "Litchfield County",
    "New Preston": "Litchfield County",
    "Newtown": "Fairfield County",
    "Niantic": "New London County",
    "Noank": "New London County",
    "Norfolk": "Litchfield County",
    "North Branford": "New Haven County",
    "North Canaan": "Litchfield County",
    "North Granby": "Hartford County",
    "North Haven": "New Haven County",
    "North Stonington": "New London County",
    "North Stamford": "Fairfield County",
    "Northwest Harwinton": "Litchfield County",
    "Norwalk": "Fairfield County",
    "Norwich": "New London County",
    "Oakdale": "New London County",
    "Oakland": "Hartford County",
    "Oakville": "Litchfield County",
    "Old Greenwich": "Fairfield County",
    "Old Lyme": "New London County",
    "Old Mystic": "New London County",
    "Old Saybrook": "Middlesex County",
    "Old Saybrook Center": "Middlesex County",
    "Orange": "New Haven County",
    "Oxoboxo River": "New London County",
    "Oxford": "New Haven County",
    "Pawcatuck": "New London County",
    "Plainfield": "Windham County",
    "Plainfield Village": "Windham County",
    "Plainville": "Hartford County",
    "Plymouth": "Litchfield County",
    "Poquonock Bridge": "New London County",
    "Pomfret": "Windham County",
    "Portland": "Middlesex County",
    "Preston": "New London County",
    "Preston City": "New London County",
    "Prospect": "New Haven County",
    "Putnam": "Windham County",
    "Redding": "Fairfield County",
    "Ridgefield": "Fairfield County",
    "Riverside": "Fairfield County",
    "Rockville": "Tolland County",
    "Rocky Hill": "Hartford County",
    "Roxbury": "Litchfield County",
    "Salem": "New London County",
    "Salmon Brook": "Hartford County",
    "Salisbury": "Litchfield County",
    "Saybrook Manor": "Middlesex County",
    "Scotland": "Windham County",
    "Seymour": "New Haven County",
    "Sharon": "Litchfield County",
    "Shelton": "Fairfield County",
    "Sherman": "Fairfield County",
    "Sherwood Manor": "Hartford County",
    "Simsbury": "Hartford County",
    "Simsbury Center": "Hartford County",
    "Somers": "Tolland County",
    "South Woodstock": "Windham County",
    "South Windham": "Windham County",
    "Southbury": "New Haven County",
    "South Coventry": "Tolland County",
    "South Windsor": "Hartford County",
    "Southwood Acres": "Hartford County",
    "Southport": "Fairfield County",
    "Sprague": "New London County",
    "Stafford": "Tolland County",
    "Stafford Springs": "Tolland County",
    "Stamford": "Fairfield County",
    "Stonington": "New London County",
    "Storrs": "Tolland County",
    "Stratford": "Fairfield County",
    "Suffield": "Hartford County",
    "Suffield Depot": "Hartford County",
    "Tariffville": "Hartford County",
    "Terramuggus": "Tolland County",
    "Terryville": "Litchfield County",
    "Thomaston": "Litchfield County",
    "Thompson": "Windham County",
    "Thompsonville": "Hartford County",
    "Tolland": "Tolland County",
    "Torrington": "Litchfield County",
    "Trumbull": "Fairfield County",
    "Union": "Tolland County",
    "Uncasville": "New London County",
    "Vernon": "Tolland County",
    "Voluntown": "New London County",
    "Wallingford": "New Haven County",
    "Wallingford Center": "New Haven County",
    "Wauregan": "Windham County",
    "Waterbury": "New Haven County",
    "Waterford": "New London County",
    "Watertown": "Litchfield County",
    "Weatogue": "Hartford County",
    "West Simsbury": "Hartford County",
    "West Torrington": "Litchfield County",
    "Westbrook": "Middlesex County",
    "Westbrook Center": "Middlesex County",
    "West Hartford": "Hartford County",
    "West Haven": "New Haven County",
    "Weston": "Fairfield County",
    "Westport": "Fairfield County",
    "Wethersfield": "Hartford County",
    "Willington": "Tolland County",
    "Willimantic": "Windham County",
    "Wilton": "Fairfield County",
    "Winchester": "Litchfield County",
    "Winsted": "Litchfield County",
    "Windham": "Windham County",
    "Windsor": "Hartford County",
    "Windsor Locks": "Hartford County",
    "Wolcott": "New Haven County",
    "Woodbridge": "New Haven County",
    "Woodmont": "New Haven County",
    "Woodbury": "Litchfield County",
    "Woodbury Center": "Litchfield County",
    "Woodstock": "Windham County"
}

town_to_planning_region = {
    "Andover": "Capitol Planning Region",
    "Ansonia": "Naugatuck Valley Planning Region",
    "Ashford": "Northeastern Connecticut Planning Region",
    "Avon": "Capitol Planning Region",
    "Baltic": "Southeastern Connecticut Planning Region",
    "Barkhamsted": "Northwest Hills Planning Region",
    "Beacon Falls": "Naugatuck Valley Planning Region",
    "Berlin": "Capitol Planning Region",
    "Bethany": "South Central Connecticut Planning Region",
    "Bethel": "Western Connecticut Planning Region",
    "Bethlehem": "Naugatuck Valley Planning Region",
    "Bethlehem Village": "Naugatuck Valley Planning Region",
    "Blue Hills": "South Central Connecticut Planning Region",
    "Bolton": "Capitol Planning Region",
    "Bozrah": "Southeastern Connecticut Planning Region",
    "Branford": "South Central Connecticut Planning Region",
    "Branford Center": "South Central Connecticut Planning Region",
    "Bridgeport": "Greater Bridgeport Planning Region",
    "Bridgewater": "Western Connecticut Planning Region",
    "Bristol": "Naugatuck Valley Planning Region",
    "Brookfield": "Western Connecticut Planning Region",
    "Brooklyn": "Northeastern Connecticut Planning Region",
    "Burlington": "Northwest Hills Planning Region",
    "Byram": "Western Connecticut Planning Region",
    "Canaan": "Northwest Hills Planning Region",
    "Canton": "Capitol Planning Region",
    "Canton Valley": "Capitol Planning Region",
    "Canterbury": "Northeastern Connecticut Planning Region",
    "Central Waterford": "Southeastern Connecticut Planning Region",
    "Chaplin": "Northeastern Connecticut Planning Region",
    "Cheshire": "Naugatuck Valley Planning Region",
    "Cheshire Village": "Naugatuck Valley Planning Region",
    "Chester": "Lower Connecticut River Valley Planning Region",
    "Chester Center": "Lower Connecticut River Valley Planning Region",
    "City of Milford (balance)" : "South Central Connecticut Planning Region",
    "Clinton": "Lower Connecticut River Valley Planning Region",
    "Colchester": "Southeastern Connecticut Planning Region",
    "Colebrook": "Northwest Hills Planning Region",
    "Collinsville": "Northwest Hills Planning Region",
    "Columbia": "Capitol Planning Region",
    "Conning Towers-Nautilus Park": "Southeastern Connecticut Planning Region",
    "Cornwall": "Northwest Hills Planning Region",
    "Cos Cob": "Western Connecticut Planning Region",
    "Coventry": "Capitol Planning Region",
    "Coventry Lake": "Capitol Planning Region",
    "Cromwell": "Lower Connecticut River Valley Planning Region",
    "Crystal Lake": "Naugatuck Valley Planning Region",
    "Danbury": "Western Connecticut Planning Region",
    "Danielson": "Northeastern Connecticut Planning Region",
    "Darien": "Western Connecticut Planning Region",
    "Deep River": "Lower Connecticut River Valley Planning Region",
    "Deep River Center": "Lower Connecticut River Valley Planning Region",
    "Derby": "Naugatuck Valley Planning Region",
    "Durham": "Lower Connecticut River Valley Planning Region",
    "Eastford": "Northeastern Connecticut Planning Region",
    "East Granby": "Capitol Planning Region",
    "East Haddam": "Lower Connecticut River Valley Planning Region",
    "East Hampton": "Lower Connecticut River Valley Planning Region",
    "East Hartford": "Capitol Planning Region",
    "East Haven": "South Central Connecticut Planning Region",
    "East Lyme": "Southeastern Connecticut Planning Region",
    "East Norwalk": "Western Connecticut Planning Region",
    "Easton": "Greater Bridgeport Planning Region",
    "East Windsor": "Capitol Planning Region",
    "Ellington": "Capitol Planning Region",
    "Enfield": "Capitol Planning Region",
    "Essex": "Lower Connecticut River Valley Planning Region",
    "Essex Village": "Lower Connecticut River Valley Planning Region",
    "Fairfield": "Greater Bridgeport Planning Region",
    "Farmington": "Capitol Planning Region",
    "Franklin": "Southeastern Connecticut Planning Region",
    "Gales Ferry": "Southeastern Connecticut Planning Region",
    "Georgetown": "Western Connecticut Planning Region",
    "Glastonbury": "Capitol Planning Region",
    "Glastonbury Center": "Capitol Planning Region",
    "Glenville": "Western Connecticut Planning Region",
    "Goshen": "Northwest Hills Planning Region",
    "Granby": "Capitol Planning Region",
    "Greenwich": "Western Connecticut Planning Region",
    "Griswold": "Southeastern Connecticut Planning Region",
    "Groton": "Southeastern Connecticut Planning Region",
    "Guilford": "South Central Connecticut Planning Region",
    "Guilford Center": "South Central Connecticut Planning Region",
    "Haddam": "Lower Connecticut River Valley Planning Region",
    "Hamden": "South Central Connecticut Planning Region",
    "Hampton": "Northeastern Connecticut Planning Region",
    "Hartford": "Capitol Planning Region",
    "Hartland": "Northwest Hills Planning Region",
    "Harwinton": "Northwest Hills Planning Region",
    "Hazardville": "Capitol Planning Region",
    "Hebron": "Capitol Planning Region",
    "Heritage Village": "Naugatuck Valley Planning Region",
    "Higganum": "Lower Connecticut River Valley Planning Region",
    "Jewett City": "Southeastern Connecticut Planning Region",
    "Kent": "Northwest Hills Planning Region",
    "Kensington": "Capitol Planning Region",
    "Killingly": "Northeastern Connecticut Planning Region",
    "Killingly Center": "Northeastern Connecticut Planning Region",
    "Killingworth": "Lower Connecticut River Valley Planning Region",
    "Lake Pocotopaug": "Capitol Planning Region",
    "Lebanon": "Southeastern Connecticut Planning Region",
    "Ledyard": "Southeastern Connecticut Planning Region",
    "Ledyard Center": "Southeastern Connecticut Planning Region",
    "Lisbon": "Southeastern Connecticut Planning Region",
    "Litchfield": "Northwest Hills Planning Region",
    "Long Hill": "Western Connecticut Planning Region",
    "Lyme": "Lower Connecticut River Valley Planning Region",
    "Madison": "South Central Connecticut Planning Region",
    "Madison Center": "South Central Connecticut Planning Region",
    "Manchester": "Capitol Planning Region",
    "Mansfield": "Capitol Planning Region",
    "Mansfield City": "Capitol Planning Region",
    "Marlborough": "Capitol Planning Region",
    "Meriden": "South Central Connecticut Planning Region",
    "Middlebury": "Naugatuck Valley Planning Region",
    "Middlefield": "Lower Connecticut River Valley Planning Region",
    "Middletown": "Lower Connecticut River Valley Planning Region",
    "Milford": "South Central Connecticut Planning Region",
    "Monroe": "Greater Bridgeport Planning Region",
    "Montville": "Southeastern Connecticut Planning Region",
    "Montville Center": "Southeastern Connecticut Planning Region",
    "Morris": "Northwest Hills Planning Region",
    "Mystic": "Southeastern Connecticut Planning Region",
    "Naugatuck": "Naugatuck Valley Planning Region",
    "Newington":"Capitol Planning Region",
    "New Britain": "Capitol Planning Region",
    "New Canaan": "Western Connecticut Planning Region",
    "New Fairfield": "Western Connecticut Planning Region",
    "New Hartford": "Northwest Hills Planning Region",
    "New Hartford Center": "Northwest Hills Planning Region",
    "New Haven": "South Central Connecticut Planning Region",
    "New London": "Southeastern Connecticut Planning Region",
    "New Milford": "Western Connecticut Planning Region",
    "New Preston": "Western Connecticut Planning Region",
    "Newtown": "Western Connecticut Planning Region",
    "Niantic": "Southeastern Connecticut Planning Region",
    "Noank": "Southeastern Connecticut Planning Region",
    "Norfolk": "Northwest Hills Planning Region",
    "North Branford": "South Central Connecticut Planning Region",
    "North Canaan": "Northwest Hills Planning Region",
    "North Granby": "Capitol Planning Region",
    "North Haven": "South Central Connecticut Planning Region",
    "North Stonington": "Southeastern Connecticut Planning Region",
    "North Stamford": "Western Connecticut Planning Region",
    "Northwest Harwinton": "Northwest Hills Planning Region",
    "Norwalk": "Western Connecticut Planning Region",
    "Norwich": "Southeastern Connecticut Planning Region",
    "Oakdale": "Western Connecticut Planning Region",
    "Oakland": "Western Connecticut Planning Region",
    "Oakville": "Naugatuck Valley Planning Region",
    "Old Greenwich": "Western Connecticut Planning Region",
    "Old Lyme": "Lower Connecticut River Valley Planning Region",
    "Old Mystic": "Southeastern Connecticut Planning Region",
    "Old Saybrook": "Lower Connecticut River Valley Planning Region",
    "Old Saybrook Center": "Lower Connecticut River Valley Planning Region",
    "Orange": "South Central Connecticut Planning Region",
    "Oxoboxo River": "Southeastern Connecticut Planning Region",
    "Oxford": "Naugatuck Valley Planning Region",
    "Pawcatuck": "Southeastern Connecticut Planning Region",
    "Plainfield": "Northeastern Connecticut Planning Region",
    "Plainfield Village": "Northeastern Connecticut Planning Region",
    "Plainville": "Capitol Planning Region",
    "Plymouth": "Naugatuck Valley Planning Region",
    "Poquonock Bridge": "Capitol Planning Region",
    "Pomfret": "Northeastern Connecticut Planning Region",
    "Portland": "Lower Connecticut River Valley Planning Region",
    "Preston": "Southeastern Connecticut Planning Region",
    "Preston City": "Southeastern Connecticut Planning Region",
    "Prospect": "Naugatuck Valley Planning Region",
    "Putnam": "Northeastern Connecticut Planning Region",
    "Redding": "Western Connecticut Planning Region",
    "Ridgefield": "Western Connecticut Planning Region",
    "Riverside": "Western Connecticut Planning Region",
    "Rockville": "Capitol Planning Region",
    "Rocky Hill": "Capitol Planning Region",
    "Roxbury": "Northwest Hills Planning Region",
    "Salem": "Southeastern Connecticut Planning Region",
    "Salmon Brook": "Capitol Planning Region",
    "Salisbury": "Northwest Hills Planning Region",
    "Saybrook Manor": "Lower Connecticut River Valley Planning Region",
    "Scotland": "Northeastern Connecticut Planning Region",
    "Seymour": "Naugatuck Valley Planning Region",
    "Sharon": "Northwest Hills Planning Region",
    "Shelton": "Naugatuck Valley Planning Region",
    "Sherman": "Western Connecticut Planning Region",
    "Sherwood Manor": "South Central Connecticut Planning Region",
    "Simsbury": "Capitol Planning Region",
    "Simsbury Center": "Capitol Planning Region",
    "Somers": "Capitol Planning Region",
    "South Woodstock": "Northeastern Connecticut Planning Region",
    "South Windham": "Northeastern Connecticut Planning Region",
    "Southbury": "Naugatuck Valley Planning Region",
    "South Coventry": "Capitol Planning Region",
    "South Windsor": "Capitol Planning Region",
    "Southwood Acres": "Capitol Planning Region",
    "Southport": "Greater Bridgeport Planning Region",
    "Sprague": "Southeastern Connecticut Planning Region",
    "Stafford": "Capitol Planning Region",
    "Stafford Springs": "Capitol Planning Region",
    "Stamford": "Western Connecticut Planning Region",
    "Stonington": "Southeastern Connecticut Planning Region",
    "Storrs": "Capitol Planning Region",
    "Stratford": "Greater Bridgeport Planning Region",
    "Suffield": "Capitol Planning Region",
    "Suffield Depot": "Capitol Planning Region",
    "Tariffville": "Capitol Planning Region",
    "Terramuggus": "Capitol Planning Region",
    "Terryville": "Naugatuck Valley Planning Region",
    "Thomaston": "Naugatuck Valley Planning Region",
    "Thompson": "Northeastern Connecticut Planning Region",
    "Thompsonville": "Capitol Planning Region",
    "Tolland": "Capitol Planning Region",
    "Torrington": "Northwest Hills Planning Region",
    "Trumbull": "Greater Bridgeport Planning Region",
    "Union": "Northeastern Connecticut Planning Region",
    "Uncasville": "Southeastern Connecticut Planning Region",
    "Vernon": "Capitol Planning Region",
    "Voluntown": "Northeastern Connecticut Planning Region",
    "Wallingford": "South Central Connecticut Planning Region",
    "Wallingford Center": "South Central Connecticut Planning Region",
    "Wauregan": "Northeastern Connecticut Planning Region",
    "Waterbury": "Naugatuck Valley Planning Region",
    "Waterford": "Southeastern Connecticut Planning Region",
    "Watertown": "Naugatuck Valley Planning Region",
    "Weatogue": "Capitol Planning Region",
    "West Simsbury": "Capitol Planning Region",
    "West Torrington": "Northwest Hills Planning Region",
    "Westbrook": "Lower Connecticut River Valley Planning Region",
    "Westbrook Center": "Lower Connecticut River Valley Planning Region",
    "West Hartford": "Capitol Planning Region",
    "West Haven": "South Central Connecticut Planning Region",
    "Weston": "Western Connecticut Planning Region",
    "Westport": "Western Connecticut Planning Region",
    "Wethersfield": "Capitol Planning Region",
    "Willington": "Capitol Planning Region",
    "Willimantic": "Capitol Planning Region",
    "Wilton": "Western Connecticut Planning Region",
    "Winchester": "Northwest Hills Planning Region",
    "Winsted": "Northwest Hills Planning Region",
    "Windham": "Southeastern Connecticut Planning Region",
    "Windsor": "Capitol Planning Region",
    "Windsor Locks": "Capitol Planning Region",
    "Wolcott": "Naugatuck Valley Planning Region",
    "Woodbridge": "South Central Connecticut Planning Region",
    "Woodmont": "Greater Bridgeport Planning Region",
    "Woodbury": "Naugatuck Valley Planning Region",
    "Woodbury Center": "Naugatuck Valley Planning Region",
    "Woodstock": "Northeastern Connecticut Planning Region"
}


state_fips = {
    "01": "ALABAMA",
    "02": "ALASKA",
    "04": "ARIZONA",
    "05": "ARKANSAS",
    "06": "CALIFORNIA",
    "08": "COLORADO",
    "09": "CONNECTICUT",
    "10": "DELAWARE",
    "12": "FLORIDA",
    "13": "GEORGIA",
    "15": "HAWAII",
    "16": "IDAHO",
    "17": "ILLINOIS",
    "18": "INDIANA",
    "19": "IOWA",
    "20": "KANSAS",
    "21": "KENTUCKY",
    "22": "LOUISIANA",
    "23": "MAINE",
    "24": "MARYLAND",
    "25": "MASSACHUSETTS",
    "26": "MICHIGAN",
    "27": "MINNESOTA",
    "28": "MISSISSIPPI",
    "29": "MISSOURI",
    "30": "MONTANA",
    "31": "NEBRASKA",
    "32": "NEVADA",
    "33": "NEW HAMPSHIRE",
    "34": "NEW JERSEY",
    "35": "NEW MEXICO",
    "36": "NEW YORK",
    "37": "NORTH CAROLINA",
    "38": "NORTH DAKOTA",
    "39": "OHIO",
    "40": "OKLAHOMA",
    "41": "OREGON",
    "42": "PENNSYLVANIA",
    "44": "RHODE ISLAND",
    "45": "SOUTH CAROLINA",
    "46": "SOUTH DAKOTA",
    "47": "TENNESSEE",
    "48": "TEXAS",
    "49": "UTAH",
    "50": "VERMONT",
    "51": "VIRGINIA",
    "53": "WASHINGTON",
    "54": "WEST VIRGINIA",
    "55": "WISCONSIN",
    "56": "WYOMING"
}
